export const TOGGLE_LOGIN_STATUS = 'TOGGLE_LOGIN_STATUS';
export const REGISTER_USER = 'REGISTER_USER';
export const VERIFY_OTP = 'VERIFY_OTP';
export const OPEN_REGISTER = 'OPEN_REGISTER';
export const OPEN_LOGIN = 'OPEN_LOGIN';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';